[package]
name = "softfig-onboard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
softfig-vault = { workspace = true }
softfig-core = { workspace = true }

include_dir = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
softfig-store = { workspace = true }
