[package]
name = "softfig-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "soft-fig CLI: vault subcommands now, more later."

[[bin]]
name = "softfig"
path = "src/main.rs"

[dependencies]
softfig-vault.workspace = true
softfig-store.workspace = true
softfig-vcs.workspace = true
softfig-ipc.workspace = true
softfig-onboard.workspace = true
softfig-deploy.workspace = true
clap.workspace = true
hostname.workspace = true
rpassword.workspace = true
anyhow.workspace = true
hex.workspace = true
zeroize.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
