//! The M5a control-plane protobuf (generated by prost from
//! `proto/control.proto`) plus small ergonomic constructors.
//!
//! Control plane only this milestone — data-plane messages (commit-push,
//! object-fetch, shared-push, ...) are defined in their own later slices.

// prost-generated code; don't hold it to our hand-written lint bar.
#[allow(clippy::all, clippy::pedantic, clippy::nursery)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/softfig.net.control.v1.rs"));
}

pub use generated::{
    frame, CommitData, DeviceStateAnnounce, Frame, GetCommit, GetObject, GetTip, GetTree,
    HelloPayload, ObjectData, Ping, Pong, RelayConnect, RelayData, ReplicaDone, ReplicaGrant,
    ShareOffer, SharedChainPush, SharedKeyCommit, SharedKeyHandoff, SharedKeyReveal, StateAnnounce,
    TipAnnounce, TreeData, TreeEntryMsg, TurnRequest, TurnRevoke, TurnYield,
};

/// Redacting `Debug` for the M5d recovery hand-off (slice 015 / LEAK-1). The
/// message carries raw `S` in `shared_key`; prost's default field-dumping
/// `Debug` is suppressed for this type in `build.rs` (`skip_debug`), so this
/// hand-written impl is the only one — it prints the framing fields but never
/// the key bytes. That makes a future `eprintln!("{frame:?}")` / panic-with-frame
/// unable to dump `S` to journald. Every enclosing type (`frame::Kind`, `Frame`,
/// `CeremonyOutcome::Handoff`) recurses through this impl for free.
impl std::fmt::Debug for SharedKeyHandoff {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SharedKeyHandoff")
            .field("chain_id", &self.chain_id)
            .field("transcript_record", &self.transcript_record)
            .field(
                "shared_key",
                &format_args!("<redacted {}B>", self.shared_key.len()),
            )
            .finish()
    }
}

impl Frame {
    /// A `Ping` control frame.
    pub fn ping(nonce: u64) -> Self {
        Self {
            kind: Some(frame::Kind::Ping(Ping { nonce })),
        }
    }

    /// A `Pong` control frame echoing `nonce`.
    pub fn pong(nonce: u64) -> Self {
        Self {
            kind: Some(frame::Kind::Pong(Pong { nonce })),
        }
    }

    /// A `StateAnnounce` frame: register reachability with the relay.
    pub fn state_announce(device_id: Vec<u8>, paired: bool) -> Self {
        Self {
            kind: Some(frame::Kind::StateAnnounce(StateAnnounce {
                device_id,
                paired,
            })),
        }
    }

    /// A `RelayConnect` frame: ask the relay to bridge to `target_device_id`.
    pub fn relay_connect(target_device_id: Vec<u8>) -> Self {
        Self {
            kind: Some(frame::Kind::RelayConnect(RelayConnect { target_device_id })),
        }
    }

    /// A `RelayData` frame carrying an opaque chunk of inner end-to-end
    /// ciphertext for the relay to forward.
    pub fn relay_data(payload: Vec<u8>) -> Self {
        Self {
            kind: Some(frame::Kind::RelayData(RelayData { payload })),
        }
    }

    // --- M5b data-plane frame constructors ---------------------------------

    /// A `ReplicaGrant` frame (owner -> host).
    pub fn replica_grant(grant: ReplicaGrant) -> Self {
        Self {
            kind: Some(frame::Kind::ReplicaGrant(grant)),
        }
    }

    /// A `GetTip` request frame (sink -> source).
    pub fn get_tip() -> Self {
        Self {
            kind: Some(frame::Kind::GetTip(GetTip {})),
        }
    }

    /// A `TipAnnounce` frame (source -> sink).
    pub fn tip_announce(ann: TipAnnounce) -> Self {
        Self {
            kind: Some(frame::Kind::TipAnnounce(ann)),
        }
    }

    /// A `GetCommit` request frame (sink -> source).
    pub fn get_commit(hash: Vec<u8>) -> Self {
        Self {
            kind: Some(frame::Kind::GetCommit(GetCommit { hash })),
        }
    }

    /// A `CommitData` response frame (source -> sink).
    pub fn commit_data(commit: CommitData) -> Self {
        Self {
            kind: Some(frame::Kind::CommitData(commit)),
        }
    }

    /// A `GetTree` request frame (sink -> source).
    pub fn get_tree(hash: Vec<u8>) -> Self {
        Self {
            kind: Some(frame::Kind::GetTree(GetTree { hash })),
        }
    }

    /// A `TreeData` response frame (source -> sink).
    pub fn tree_data(tree: TreeData) -> Self {
        Self {
            kind: Some(frame::Kind::TreeData(tree)),
        }
    }

    /// A `GetObject` request frame (sink -> source).
    pub fn get_object(hash: Vec<u8>) -> Self {
        Self {
            kind: Some(frame::Kind::GetObject(GetObject { hash })),
        }
    }

    /// An `ObjectData` response frame (source -> sink).
    pub fn object_data(object: ObjectData) -> Self {
        Self {
            kind: Some(frame::Kind::ObjectData(object)),
        }
    }

    /// A `ReplicaDone` frame (sink -> source).
    pub fn replica_done() -> Self {
        Self {
            kind: Some(frame::Kind::ReplicaDone(ReplicaDone {})),
        }
    }

    // --- M5d shared-key ceremony frame constructors ------------------------

    /// A `SharedKeyCommit` frame (member -> members): a signed commitment
    /// broadcast in the commit phase.
    pub fn shared_key_commit(commit: SharedKeyCommit) -> Self {
        Self {
            kind: Some(frame::Kind::SharedKeyCommit(commit)),
        }
    }

    /// A `SharedKeyReveal` frame (member -> members): the signed reveal of a
    /// member's contribution in the reveal phase.
    pub fn shared_key_reveal(reveal: SharedKeyReveal) -> Self {
        Self {
            kind: Some(frame::Kind::SharedKeyReveal(reveal)),
        }
    }

    /// A `SharedKeyHandoff` frame (keyed member -> stranded member): the M5d
    /// slice-008 recovery response carrying the committed transcript + `S`.
    pub fn shared_key_handoff(handoff: SharedKeyHandoff) -> Self {
        Self {
            kind: Some(frame::Kind::SharedKeyHandoff(handoff)),
        }
    }

    // --- M5e write-turn coordination frame constructors --------------------

    /// A `DeviceStateAnnounce` frame (member -> members): this device's
    /// offline / online-idle / online-active state (+ unlocked flag).
    pub fn device_state_announce(announce: DeviceStateAnnounce) -> Self {
        Self {
            kind: Some(frame::Kind::DeviceStateAnnounce(announce)),
        }
    }

    /// A `TurnRequest` frame (member -> members): request a chain's write turn.
    pub fn turn_request(request: TurnRequest) -> Self {
        Self {
            kind: Some(frame::Kind::TurnRequest(request)),
        }
    }

    /// A `TurnYield` frame (holder -> requester): yield the turn (the go-ahead).
    pub fn turn_yield(yield_: TurnYield) -> Self {
        Self {
            kind: Some(frame::Kind::TurnYield(yield_)),
        }
    }

    /// A `TurnRevoke` frame (member -> members): an expired holder's lease is
    /// reclaimed so the turn returns.
    pub fn turn_revoke(revoke: TurnRevoke) -> Self {
        Self {
            kind: Some(frame::Kind::TurnRevoke(revoke)),
        }
    }

    /// A `SharedChainPush` frame (writer -> S-members): a committed shared-subtree
    /// edit to adopt (M5e slice 002 shared-pull).
    pub fn shared_chain_push(push: SharedChainPush) -> Self {
        Self {
            kind: Some(frame::Kind::SharedChainPush(push)),
        }
    }

    // --- M5f share-offer frame constructor ---------------------------------

    /// A `ShareOffer` frame (sharer -> ring): a share a recipient may accept +
    /// place at its own path (M5f slice 003).
    pub fn share_offer(offer: ShareOffer) -> Self {
        Self {
            kind: Some(frame::Kind::ShareOffer(offer)),
        }
    }
}

impl HelloPayload {
    /// Build the in-handshake identity payload at the current protocol version.
    /// `device_id` is the device's Ed25519 identity public key. The
    /// `static_attestation` (field 4) starts empty; the pairing layer fills it
    /// with the Ed25519 signature over the X25519 static (see
    /// [`crate::pairing::LocalDevice`]).
    pub fn new(device_id: Vec<u8>, device_name: impl Into<String>) -> Self {
        Self {
            protocol_version: crate::PROTOCOL_VERSION,
            device_id,
            device_name: device_name.into(),
            static_attestation: Vec::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    /// m5f slice 002 — placement never crosses the wire. A member's mount path
    /// is per-device state ([[decision-shared-subtree-recipient-placement]]);
    /// what the ring agrees on is the share's identity (plus the advisory
    /// recommendation, slice 003) — never where any device mounted it. This
    /// tripwire fails the moment a `mount_path` field lands in the wire schema,
    /// so the addition has to confront the decision.
    #[test]
    fn no_wire_message_declares_a_mount_path_field() {
        let proto = include_str!("../proto/control.proto");
        for line in proto.lines() {
            // Declarations only — a comment may *discuss* mount paths.
            let code = line.split("//").next().unwrap_or(line);
            assert!(
                !code.contains("mount_path"),
                "placement leaked into the wire schema: {line}"
            );
        }
    }
}
