//! The M5a control-plane protobuf (generated by prost from
//! `proto/control.proto`) plus small ergonomic constructors.
//!
//! Control plane only this milestone — data-plane messages (commit-push,
//! object-fetch, shared-push, ...) are defined in their own later slices.

// prost-generated code; don't hold it to our hand-written lint bar.
#[allow(clippy::all, clippy::pedantic, clippy::nursery)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/softfig.net.control.v1.rs"));
}

pub use generated::{frame, Frame, HelloPayload, Ping, Pong};

impl Frame {
    /// A `Ping` control frame.
    pub fn ping(nonce: u64) -> Self {
        Self {
            kind: Some(frame::Kind::Ping(Ping { nonce })),
        }
    }

    /// A `Pong` control frame echoing `nonce`.
    pub fn pong(nonce: u64) -> Self {
        Self {
            kind: Some(frame::Kind::Pong(Pong { nonce })),
        }
    }
}

impl HelloPayload {
    /// Build the in-handshake identity payload at the current protocol version.
    /// `device_id` is the device's Ed25519 identity public key.
    pub fn new(device_id: Vec<u8>, device_name: impl Into<String>) -> Self {
        Self {
            protocol_version: crate::PROTOCOL_VERSION,
            device_id,
            device_name: device_name.into(),
        }
    }
}
