//! The M5a control-plane protobuf (generated by prost from
//! `proto/control.proto`) plus small ergonomic constructors.
//!
//! Control plane only this milestone — data-plane messages (commit-push,
//! object-fetch, shared-push, ...) are defined in their own later slices.

// prost-generated code; don't hold it to our hand-written lint bar.
#[allow(clippy::all, clippy::pedantic, clippy::nursery)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/softfig.net.control.v1.rs"));
}

pub use generated::{
    frame, CommitData, Frame, GetCommit, GetObject, GetTip, GetTree, HelloPayload, ObjectData,
    Ping, Pong, RelayConnect, RelayData, ReplicaDone, ReplicaGrant, StateAnnounce, TipAnnounce,
    TreeData, TreeEntryMsg,
};

impl Frame {
    /// A `Ping` control frame.
    pub fn ping(nonce: u64) -> Self {
        Self {
            kind: Some(frame::Kind::Ping(Ping { nonce })),
        }
    }

    /// A `Pong` control frame echoing `nonce`.
    pub fn pong(nonce: u64) -> Self {
        Self {
            kind: Some(frame::Kind::Pong(Pong { nonce })),
        }
    }

    /// A `StateAnnounce` frame: register reachability with the relay.
    pub fn state_announce(device_id: Vec<u8>, paired: bool) -> Self {
        Self {
            kind: Some(frame::Kind::StateAnnounce(StateAnnounce {
                device_id,
                paired,
            })),
        }
    }

    /// A `RelayConnect` frame: ask the relay to bridge to `target_device_id`.
    pub fn relay_connect(target_device_id: Vec<u8>) -> Self {
        Self {
            kind: Some(frame::Kind::RelayConnect(RelayConnect { target_device_id })),
        }
    }

    /// A `RelayData` frame carrying an opaque chunk of inner end-to-end
    /// ciphertext for the relay to forward.
    pub fn relay_data(payload: Vec<u8>) -> Self {
        Self {
            kind: Some(frame::Kind::RelayData(RelayData { payload })),
        }
    }

    // --- M5b data-plane frame constructors ---------------------------------

    /// A `ReplicaGrant` frame (owner -> host).
    pub fn replica_grant(grant: ReplicaGrant) -> Self {
        Self {
            kind: Some(frame::Kind::ReplicaGrant(grant)),
        }
    }

    /// A `GetTip` request frame (sink -> source).
    pub fn get_tip() -> Self {
        Self {
            kind: Some(frame::Kind::GetTip(GetTip {})),
        }
    }

    /// A `TipAnnounce` frame (source -> sink).
    pub fn tip_announce(ann: TipAnnounce) -> Self {
        Self {
            kind: Some(frame::Kind::TipAnnounce(ann)),
        }
    }

    /// A `GetCommit` request frame (sink -> source).
    pub fn get_commit(hash: Vec<u8>) -> Self {
        Self {
            kind: Some(frame::Kind::GetCommit(GetCommit { hash })),
        }
    }

    /// A `CommitData` response frame (source -> sink).
    pub fn commit_data(commit: CommitData) -> Self {
        Self {
            kind: Some(frame::Kind::CommitData(commit)),
        }
    }

    /// A `GetTree` request frame (sink -> source).
    pub fn get_tree(hash: Vec<u8>) -> Self {
        Self {
            kind: Some(frame::Kind::GetTree(GetTree { hash })),
        }
    }

    /// A `TreeData` response frame (source -> sink).
    pub fn tree_data(tree: TreeData) -> Self {
        Self {
            kind: Some(frame::Kind::TreeData(tree)),
        }
    }

    /// A `GetObject` request frame (sink -> source).
    pub fn get_object(hash: Vec<u8>) -> Self {
        Self {
            kind: Some(frame::Kind::GetObject(GetObject { hash })),
        }
    }

    /// An `ObjectData` response frame (source -> sink).
    pub fn object_data(object: ObjectData) -> Self {
        Self {
            kind: Some(frame::Kind::ObjectData(object)),
        }
    }

    /// A `ReplicaDone` frame (sink -> source).
    pub fn replica_done() -> Self {
        Self {
            kind: Some(frame::Kind::ReplicaDone(ReplicaDone {})),
        }
    }
}

impl HelloPayload {
    /// Build the in-handshake identity payload at the current protocol version.
    /// `device_id` is the device's Ed25519 identity public key. The
    /// `static_attestation` (field 4) starts empty; the pairing layer fills it
    /// with the Ed25519 signature over the X25519 static (see
    /// [`crate::pairing::LocalDevice`]).
    pub fn new(device_id: Vec<u8>, device_name: impl Into<String>) -> Self {
        Self {
            protocol_version: crate::PROTOCOL_VERSION,
            device_id,
            device_name: device_name.into(),
            static_attestation: Vec::new(),
        }
    }
}
