//! growlight Phase 2 — `softfig growlight init`, the pillar scaffolder.
//!
//! Idempotent retrofit (mirrors `migrate split`): materializes the `growlight/`
//! pillar via the same write/commit machinery as the Phase-1 MCP verbs, writes
//! the two embedded templates (`protocol.md`, `session-policy.md`), and performs
//! the spec §14 nav wiring (root `CLAUDE.md` top-level map + boundary row,
//! `meta/reserved-filenames.md`, `meta/conventions.md`). The garden/runtime
//! split is honoured: only the durable garden pillar is created here — the
//! churny runtime (`baton.md`, `usage.json`, `loop.json`, `questions.md` under
//! `$XDG_CONFIG_HOME/softfig/growlight/`) belongs to the Phase-2b launcher and
//! is written CLI-side, never committed.
//!
//! Everything folds into one `growlight_initialized` commit. A re-run on an
//! already-scaffolded garden creates nothing and makes no commit (no empty
//! commits) — only the missing pieces are filled, so the action is also
//! self-healing for a partially-built pillar.

use std::path::Path;

use softfig_vcs::Intent;
use softfig_ipc::verbs::{GrowlightInitArgs, GrowlightInitReply};
use softfig_ipc::ErrorKind;

use super::super::{commit_now, write_file};
use super::paths;
use crate::daemon::{Daemon, DaemonInner};
use crate::handlers::{require_unlocked, HandlerResult};
use crate::server::err_to_response;

// ---- embedded templates (spec §11: "from embedded templates") ----------

/// The fixed operating contract, injected into every loop session (spec §7).
const PROTOCOL_MD: &str =
    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/growlight/protocol.md"));
/// The editable two-budget policy (spec §8).
const SESSION_POLICY_MD: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../templates/growlight/session-policy.md"
));

// ---- nav-wiring content (spec §14) -------------------------------------

/// Boundary-table heading in both the prototype and default-garden `CLAUDE.md`.
const BOUNDARY_HEADING: &str = "Where does X belong? (boundary decision table)";

const MAP_BULLET: &str = "- `growlight/` — the autonomous work-loop pillar: protocol, backlog \
(milestones + tasks), and the append-only baton-log. Set up by `softfig growlight init`, driven \
by `softfig growlight start`.";

const BOUNDARY_ROW: &str = "| the autonomous work loop, the build queue/baton, handing off \
between sessions | `growlight/` | `meta/spec-growlight.md` for the design |";

const RESERVED_HEADING: &str = "growlight pillar reserved names";
const RESERVED_BODY: &str = "The growlight work-loop pillar (`growlight/`, set up by \
`softfig growlight init`) reserves four more names *within it*:\n\n\
- `backlog/` — the work queue (milestones + tasks); status/order live in its managed queue \
table.\n\
- `baton-log/` — append-only numbered iteration entries (audit; never injected).\n\
- `protocol.md` — the fixed loop operating contract, injected each session.\n\
- `session-policy.md` — the editable two-budget policy.\n\n\
See `meta/spec-growlight.md` and `journal/decisions/decision-growlight-loop.md`.";

const CONVENTIONS_HEADING: &str = "Agent runtime state lives outside the garden";
const CONVENTIONS_BODY: &str = "The `growlight/` work-loop pillar holds **durable** loop \
knowledge (protocol, backlog, baton-log) in the garden, but the loop's **churny runtime** — the \
current baton, the budget `usage.json`, the offline `questions.md` form, and the generated \
launcher settings — does **not** live in the garden. It lives in the app's own config namespace \
(`$XDG_CONFIG_HOME/softfig/growlight/`), regenerated by the app and never hand-placed.\n\n\
This is a deliberate exception to \"concept folders hold stable knowledge; `snapshots/` holds \
mutating state\": that rule covers state worth versioning in the garden, whereas agent scratch is \
disposable per-session runtime, not garden history. See `meta/spec-growlight.md` and \
`journal/decisions/decision-growlight-loop.md`.";

// ---- handler -----------------------------------------------------------

pub fn growlight_init(daemon: &Daemon, args: serde_json::Value) -> HandlerResult {
    let _args: GrowlightInitArgs = serde_json::from_value(args)
        .map_err(|e| (ErrorKind::BadArgs, format!("growlight_init args: {e}")))?;

    let mut inner = daemon.inner.lock().unwrap();
    require_unlocked(&inner)?;
    let garden_root = inner.config.garden_root.clone();

    let mut created = Vec::new();
    let mut skipped = Vec::new();

    // Pillar files (create-if-absent; status/order in backlog/CLAUDE.md is
    // never clobbered if the MCP verbs already seeded it). The numbered folders
    // get a `.seq` seed so their first entry counts from 001, materializing the
    // dir as a tracked entity at the same time.
    let pillar: [(String, String); 7] = [
        (paths::pillar_claude(), paths::pillar_claude_stub()),
        (paths::protocol_md(), PROTOCOL_MD.to_string()),
        (paths::session_policy_md(), SESSION_POLICY_MD.to_string()),
        (paths::backlog_claude(), paths::backlog_claude_stub()),
        (format!("{}/.seq", paths::tasks_dir()), "0\n".to_string()),
        (paths::baton_log_claude(), paths::baton_log_claude_stub()),
        (format!("{}/.seq", paths::baton_log_dir()), "0\n".to_string()),
    ];
    for (rel, content) in &pillar {
        create_if_absent(daemon, &garden_root, rel, content, &mut created, &mut skipped)?;
    }

    // §14 nav wiring — best-effort + idempotent. Each edit is skipped when the
    // doc is absent (a minimal garden), sealed, or already wired.
    let mut nav_wired = Vec::new();
    wire_nav_doc(daemon, &inner, &garden_root, "CLAUDE.md", &mut nav_wired, |content| {
        let mut doc = content.to_string();
        let mut changed = false;
        if let Some(new) =
            nav::insert_after_last_prefixed(&doc, "Top-level map", "- ", "growlight/", MAP_BULLET)
        {
            doc = new;
            changed = true;
        }
        if let Some(new) =
            nav::insert_after_last_prefixed(&doc, BOUNDARY_HEADING, "|", "growlight/", BOUNDARY_ROW)
        {
            doc = new;
            changed = true;
        }
        changed.then_some(doc)
    })?;
    wire_nav_doc(
        daemon,
        &inner,
        &garden_root,
        "meta/reserved-filenames.md",
        &mut nav_wired,
        |content| add_section_opt(content, RESERVED_HEADING, RESERVED_BODY),
    )?;
    wire_nav_doc(
        daemon,
        &inner,
        &garden_root,
        "meta/conventions.md",
        &mut nav_wired,
        |content| add_section_opt(content, CONVENTIONS_HEADING, CONVENTIONS_BODY),
    )?;

    // Nothing to do → don't mint an empty commit (mirrors set_item_status).
    if created.is_empty() && nav_wired.is_empty() {
        let tip = current_tip(&inner)?;
        return Ok(serde_json::to_value(GrowlightInitReply {
            created,
            skipped,
            nav_wired,
            committed: false,
            hash: tip,
        })
        .unwrap());
    }

    let payload = serde_json::json!({ "created": created, "nav_wired": nav_wired });
    let intent = Intent::new("growlight_initialized", payload)
        .map_err(|e| (ErrorKind::Internal, e.to_string()))?;
    let hash = commit_now(&mut inner, intent)?;

    Ok(serde_json::to_value(GrowlightInitReply {
        created,
        skipped,
        nav_wired,
        committed: true,
        hash: hash.to_string(),
    })
    .unwrap())
}

// ---- helpers -----------------------------------------------------------

/// Write `content` to `rel` only if it doesn't already exist, recording the
/// outcome and registering the path for self-write suppression.
fn create_if_absent(
    daemon: &Daemon,
    garden_root: &Path,
    rel: &str,
    content: &str,
    created: &mut Vec<String>,
    skipped: &mut Vec<String>,
) -> Result<(), (ErrorKind, String)> {
    let abs = garden_root.join(rel);
    if abs.exists() {
        skipped.push(rel.to_string());
        return Ok(());
    }
    daemon.mark_self_write(abs.clone());
    write_file(&abs, content.as_bytes())?;
    created.push(rel.to_string());
    Ok(())
}

/// Read an existing nav doc (skipping absent/sealed/non-UTF-8 ones), apply
/// `edit`, and write it back when `edit` reports a change. Best-effort: a
/// missing doc on a minimal garden is a no-op, not an error.
fn wire_nav_doc(
    daemon: &Daemon,
    inner: &DaemonInner,
    garden_root: &Path,
    rel: &str,
    nav_wired: &mut Vec<String>,
    edit: impl FnOnce(&str) -> Option<String>,
) -> Result<(), (ErrorKind, String)> {
    let abs = garden_root.join(rel);
    let Some(content) = crate::actions::sections::read_if_unprotected(inner, &abs, rel) else {
        return Ok(());
    };
    if let Some(new) = edit(&content) {
        daemon.mark_self_write(abs.clone());
        write_file(&abs, new.as_bytes())?;
        nav_wired.push(rel.to_string());
    }
    Ok(())
}

/// `add_section`, mapping any error (incl. an already-present heading) to
/// `None` so the nav wiring stays idempotent + best-effort.
fn add_section_opt(content: &str, heading: &str, body: &str) -> Option<String> {
    crate::actions::sections::edit::add_section(content, heading, body).ok()
}

/// The current tip as a hex string (empty if there are no commits yet).
fn current_tip(inner: &DaemonInner) -> Result<String, (ErrorKind, String)> {
    Ok(inner
        .repo
        .as_ref()
        .expect("unlocked")
        .tip()
        .map_err(|e| err_to_response(e.into()))?
        .map(|h| h.to_string())
        .unwrap_or_default())
}

// ---- pure nav-table editing -------------------------------------------
//
// Split out so it's daemon-free unit-testable. The transforms target the two
// shared headings present in both the prototype and the default-garden
// `CLAUDE.md`; everything outside the touched line is byte-preserved across the
// `split('\n')` / `join('\n')` round-trip.

mod nav {
    /// Parse an ATX heading line → `(level, text)`. `None` for a non-heading
    /// (`#hashtag`, `#!/bin/sh`, plain text).
    fn atx(line: &str) -> Option<(usize, &str)> {
        let t = line.trim_start();
        let hashes = t.bytes().take_while(|&b| b == b'#').count();
        if hashes == 0 || hashes > 6 {
            return None;
        }
        let rest = &t[hashes..];
        if rest.is_empty() {
            return Some((hashes, ""));
        }
        if !rest.starts_with(' ') {
            return None;
        }
        Some((hashes, rest.trim()))
    }

    /// `[heading_line, section_end)` for the first section whose heading text
    /// equals `heading`, fence-aware. `None` if the heading is absent.
    fn section_range(lines: &[&str], heading: &str) -> Option<(usize, usize)> {
        let mut in_fence = false;
        let mut start = None;
        for (i, line) in lines.iter().enumerate() {
            let t = line.trim_start();
            if t.starts_with("```") || t.starts_with("~~~") {
                in_fence = !in_fence;
                continue;
            }
            if in_fence {
                continue;
            }
            if let Some((level, text)) = atx(line) {
                if text == heading {
                    start = Some((i, level));
                    break;
                }
            }
        }
        let (hline, hlevel) = start?;
        let mut in_fence = false;
        let mut end = lines.len();
        for (i, line) in lines.iter().enumerate().skip(hline + 1) {
            let t = line.trim_start();
            if t.starts_with("```") || t.starts_with("~~~") {
                in_fence = !in_fence;
                continue;
            }
            if in_fence {
                continue;
            }
            if let Some((level, _)) = atx(line) {
                if level <= hlevel {
                    end = i;
                    break;
                }
            }
        }
        Some((hline, end))
    }

    /// Insert `new_line` immediately after the last line in section `heading`
    /// whose trimmed text starts with `line_prefix` (a list bullet `- `, or a
    /// table row `|`). `None` — leaving the doc untouched — if the section is
    /// absent, already contains `marker`, or has no `line_prefix` line. This is
    /// what makes the wiring idempotent and table/list aware (naive
    /// section-append would land after the section's trailing prose / `---`).
    pub fn insert_after_last_prefixed(
        content: &str,
        heading: &str,
        line_prefix: &str,
        marker: &str,
        new_line: &str,
    ) -> Option<String> {
        let lines: Vec<&str> = content.split('\n').collect();
        let (hline, end) = section_range(&lines, heading)?;
        if lines[hline..end].iter().any(|l| l.contains(marker)) {
            return None;
        }
        let pos = (hline + 1..end)
            .rev()
            .find(|&i| lines[i].trim_start().starts_with(line_prefix))?;
        let mut out: Vec<String> = lines[..=pos].iter().map(|s| s.to_string()).collect();
        out.push(new_line.to_string());
        out.extend(lines[pos + 1..].iter().map(|s| s.to_string()));
        Some(out.join("\n"))
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        // A doc shaped like the default-garden CLAUDE.md: a boundary table that
        // is followed by prose, then a top-level map of bullets followed by a
        // `---` rule. Both traps that defeat a naive section-append.
        const DOC: &str = "# garden\n\n\
            ## Where does X belong? (boundary decision table)\n\n\
            intro line\n\n\
            | about | read | then |\n\
            |---|---|---|\n\
            | packages | `packages/` | snap |\n\
            | how the garden works | `meta/` | — |\n\n\
            Boundary rule: own each concept once.\n\n\
            ---\n\n\
            ## Top-level map\n\n\
            - `meta/` — docs about the garden.\n\
            - `journal/` — dated decisions.\n\n\
            ---\n\n\
            ## How to behave\n\n\
            do things\n";

        #[test]
        fn map_bullet_lands_after_last_bullet_not_after_the_rule() {
            let out = insert_after_last_prefixed(DOC, "Top-level map", "- ", "growlight/", "- NEW")
                .unwrap();
            assert!(out.contains("- `journal/` — dated decisions.\n- NEW\n"));
            // The trailing `---` and the next heading are untouched.
            assert!(out.contains("- NEW\n\n---\n\n## How to behave"));
        }

        #[test]
        fn table_row_lands_after_last_row_not_after_the_prose() {
            let out = insert_after_last_prefixed(DOC, BOUNDARY, "|", "growlight/", "| R |").unwrap();
            assert!(out.contains("| how the garden works | `meta/` | — |\n| R |\n"));
            assert!(out.contains("| R |\n\nBoundary rule:"));
        }

        const BOUNDARY: &str = "Where does X belong? (boundary decision table)";

        #[test]
        fn idempotent_when_marker_present() {
            let once =
                insert_after_last_prefixed(DOC, "Top-level map", "- ", "growlight/", "- `growlight/` x")
                    .unwrap();
            assert!(
                insert_after_last_prefixed(&once, "Top-level map", "- ", "growlight/", "- `growlight/` x")
                    .is_none()
            );
        }

        #[test]
        fn absent_section_or_prefix_is_none() {
            assert!(insert_after_last_prefixed(DOC, "No Such Heading", "- ", "x", "- y").is_none());
            // A section with no matching prefixed line (How to behave has prose).
            assert!(insert_after_last_prefixed(DOC, "How to behave", "|", "x", "| y |").is_none());
        }

        #[test]
        fn headings_inside_a_fence_do_not_end_the_section() {
            let doc = "## Top-level map\n\n- a\n\n```\n## fake\n```\n\n- b\n\n## Real\n\nx\n";
            let out =
                insert_after_last_prefixed(doc, "Top-level map", "- ", "zz", "- c").unwrap();
            // The fenced `## fake` is not a heading, so `- b` is still in-section.
            assert!(out.contains("- b\n- c\n"));
        }
    }
}
